### ISSUE TITLE
CRITICAL Uncaught Error

### ISSUE THREAD

**Issue by rifatspir** [sslcommerz/New-WooCommerce-PaymentGateway-V5.2.1-Hosted#4]
Please fix this error in next update.

CRITICAL Uncaught Error: Call to a member function get_total() on bool in /wp-content/plugins/New-WooCommerce-PaymentGateway-V5.2.1-Hosted-master/sslcommerz_ipn.php:48

**Comment by rifatspir** [comment]
CRITICAL Uncaught Error: Call to a member function get_total() on bool in /home/example/public_html/wp-content/plugins/New-WooCommerce-PaymentGateway-V5.2.1-Hosted-master/sslcommerz_ipn.php:48
Stack trace:
#0 /home/example/public_html/wp-content/plugins/New-WooCommerce-PaymentGateway-V5.2.1-Hosted-master/index.php(613): include()
#1 /home/example/public_html/wp-includes/class-wp-hook.php(287): Create_ssl_ipn_page_url->parse_request(Object(WP))
#2 /home/example/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/example/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#4 /home/example/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#5 /home/example/public_html/wp-includes/class-wp.php(735): WP->parse_request('')
#6 /home/example/public_html/wp-includes/functions.php(1274): WP->main('')
#7 /home/example/public_html/wp-blog-header.php(16): wp()
#8 /home/example/public_html/index.php(17): require('/home/example/... in /home/example/public_html/wp-content/plugins/New-WooCommerce-PaymentGateway-V5.2.1-Hosted-master/sslcommerz_ipn.php on line 48
